### ISSUE TITLE
vstack issue

### ISSUE THREAD

**Issue by micklavner** [bikz05/bag-of-words#1]
Hi,

First thanks the script seems quite nice.
I try to run it with 103 classes, so i basically replaced the folder in train directory by new folders, named after my classes, and containing 50 images each.
So, as guessed, it take 45/50min to run... but then i always get that error : "ValueError: all the input array dimensions except for the concatenation axis must match exactly" the error comes from ligne 50 when stacking the descriptors...

My folders are as the picture... any idea what is wrong??

![capture d ecran 2015-06-01 a 00 59 07](https://cloud.githubusercontent.com/assets/3824095/7904410/6ddb00e2-07f9-11e5-9150-fbab5fa128e0.png)

ps : when using your code "out of the box" it runs perfectly

PS2 : solved it

**Comment by bikz05** [comment]
Hey,
Sorry, I couldn't reply earlier. Okay, so it appears that everything is okay. I am closing the issue as of now. If there are any other issue, please let me know.
Thank You

**Comment by micklavner** [comment]
Hey, 

No trouble, i think one of my picture was wrong… as soon as i deleted the all the images of the folder causing issue and replaced all the images of a class it seems to work…
I just started the find features script.
If it doesn’t work i’ll mail you or start an issue on github!

Thanks for your mail !!
