### ISSUE TITLE
module 'cv2' has no attribute 'FeatureDetector_create'

### ISSUE THREAD

**Issue by shrestharikesh** [bikz05/bag-of-words#15]
Traceback (most recent call last):
  File "findFeatures.py", line 35, in <module>
    fea_det = cv2.FeatureDetector_create("SIFT")
AttributeError: module 'cv2' has no attribute 'FeatureDetector_create'

**Comment by nedufural** [comment]
You should use cv2.xfeatures2d.SIFT_create() instead.

**Comment by chifaa** [comment]
> You should use cv2.xfeatures2d.SIFT_create() instead.

plz give more explication ;thx
