### ISSUE TITLE
'LinearSVC' object has no attribute 'classes_'

### ISSUE THREAD

**Issue by powderblock** [bikz05/bag-of-words#4]
I get this error when trying to run `getClass.py` with the args -t dataset/test --visualize.
I think this is an issue with LinearSVC and not my end, but I wanted to make sure.

`predictions =  [classes_names[i] for i in clf.predict(test_features)]
  File "C:\Python27\lib\site-packages\sklearn\linear_model\base.py", line 228, in predict
    return self._classes_[indices]
AttributeError: 'LinearSVC' object has no attribute 'classes_'`

 Anyone having this issue?

**Comment by powderblock** [comment]
This fixed itself, which is weird.

I re-trained in and now it no longer happens. Huh.

**Comment by orensig** [comment]
@powderblock Hi, how did you retrain the model? I need to do same
