### ISSUE TITLE
I want to run them from another Python Script

### ISSUE THREAD

**Issue by sezan92** [bikz05/bag-of-words#5]
Hello! You've done a wonderful job! I wanted to run these codes from another python scripts. How should I do it ? Please Help! :)

**Comment by bikz05** [comment]
Hi there, 

I haven't written the code in a way that you can call it from other scripts. Apologies for that. But will do it, once I get time. 

Having said that, I don't think it's tough to do that. You just need to convert the code into function and call the functions.

**Comment by sezan92** [comment]
I tried that, but that didnt work for some unknown reasons!
