### ISSUE TITLE
core dumped

### ISSUE THREAD

**Issue by CoreOne23** [bikz05/bag-of-words#6]
When i am excecuting 

> python findFeatures.py -t dataset/train/
> it shows -
> Segmentation fault (core dumped)

plz help.

**Comment by bikz05** [comment]
Which version of OpenCV are you using? If it is 3, then SIFT might be the problem because they moved it now to `opencv_contrib`. In that case, you might have to change some code.

**Comment by CoreOne23** [comment]
thanks for replying.
I got the problem solved after installing non_free lib for opencv.
