### ISSUE TITLE
issue while trainig the data

### ISSUE THREAD

**Issue by MayankSharma-MS** [bikz05/bag-of-words#7]
I got this error while training the data, please help!! 

File "findFeatures.py", line 50, in <module>
    descriptors = np.vstack((descriptors, descriptor))
  File "/usr/lib/python2.7/dist-packages/numpy/core/shape_base.py", line 228, in vstack
    return _nx.concatenate([atleast_2d(_m) for _m in tup], 0)
ValueError: all the input array dimensions except for the concatenation axis must match exactly

**Comment by bikz05** [comment]
Based on #3 looks like your images are not at the right place. Try to check the path.
